Rich:
  x:
    - probe_Brunel_P
    - probe_Brunel_ETA
    - nTracks_Brunel
    - probe_Brunel_trackcharge
  y:
    - probe_Brunel_RichDLLe
    - probe_Brunel_RichDLLmu
    - probe_Brunel_RichDLLk
    - probe_Brunel_RichDLLp
  w:
    - probe_sWeight

Muon:
  x:
    - probe_Brunel_P
    - probe_Brunel_ETA
    - nTracks_Brunel
    - probe_Brunel_trackcharge
  y:
    - probe_Brunel_MuonMuLL
    - probe_Brunel_MuonBgLL
  w:
    - probe_sWeight

GlobalPIDmu:
  x:
    - probe_Brunel_P
    - probe_Brunel_ETA
    - nTracks_Brunel
    - probe_Brunel_trackcharge
    - probe_Brunel_RichDLLe
    - probe_Brunel_RichDLLmu
    - probe_Brunel_RichDLLk
    - probe_Brunel_RichDLLp
    - probe_Brunel_MuonMuLL
    - probe_Brunel_MuonBgLL
  y:
    - probe_Brunel_PIDe
    - probe_Brunel_PIDK
    - probe_Brunel_PIDp
    - probe_Brunel_MC15TuneV1_ProbNNe
    - probe_Brunel_MC15TuneV1_ProbNNpi
    - probe_Brunel_MC15TuneV1_ProbNNk
    - probe_Brunel_MC15TuneV1_ProbNNp
    - probe_Brunel_PIDmu
    - probe_Brunel_MC15TuneV1_ProbNNmu
  w:
    - probe_sWeight

GlobalPIDh:
  x:
    - probe_Brunel_P
    - probe_Brunel_ETA
    - nTracks_Brunel
    - probe_Brunel_trackcharge
    - probe_Brunel_RichDLLe
    - probe_Brunel_RichDLLmu
    - probe_Brunel_RichDLLk
    - probe_Brunel_RichDLLp

  y:
    - probe_Brunel_PIDe
    - probe_Brunel_PIDK
    - probe_Brunel_PIDp
    - probe_Brunel_MC15TuneV1_ProbNNe
    - probe_Brunel_MC15TuneV1_ProbNNpi
    - probe_Brunel_MC15TuneV1_ProbNNk
    - probe_Brunel_MC15TuneV1_ProbNNp
    - probe_Brunel_PIDmu
  w:
    - probe_sWeight

isMuon:
  x:
    - probe_Brunel_P
    - probe_Brunel_ETA
    - nTracks_Brunel
    - probe_Brunel_trackcharge
  y:
    - probe_Brunel_isMuon
  w:
    - probe_sWeight  
