# style.yml

name: style

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set-up python version
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"  # supported by all tensorflow versions
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements/style.txt
    - name: Run ruff checks
      run: ruff check --diff src/ tests/ scripts/
